In [1]:
import pandas as pd
import numpy as np

In [2]:
drug = pd.read_csv('datasets/drug-use-by-age.csv', index_col=0) #Remove the index , index_col=0)

drug.head()

,n,alcohol-use,alcohol-frequency,marijuana-use,marijuana-frequency,cocaine-use,cocaine-frequency,crack-use,crack-frequency,heroin-use,...,oxycontin-use,oxycontin-frequency,tranquilizer-use,tranquilizer-frequency,stimulant-use,stimulant-frequency,meth-use,meth-frequency,sedative-use,sedative-frequency
age,,,,,,,,,,,,,,,,,,,,,
12,2798,3.9,3.0,1.1,4.0,0.1,5.0,0.0,-,0.1,...,0.1,24.5,0.2,52.0,0.2,2.0,0.0,-,0.2,13.0
13,2757,8.5,6.0,3.4,15.0,0.1,1.0,0.0,3.0,0.0,...,0.1,41.0,0.3,25.5,0.3,4.0,0.1,5.0,0.1,19.0
14,2792,18.1,5.0,8.7,24.0,0.1,5.5,0.0,-,0.1,...,0.4,4.5,0.9,5.0,0.8,12.0,0.1,24.0,0.2,16.5
15,2956,29.2,6.0,14.5,25.0,0.5,4.0,0.1,9.5,0.2,...,0.8,3.0,2.0,4.5,1.5,6.0,0.3,10.5,0.4,30.0
16,3058,40.1,10.0,22.5,30.0,1.0,7.0,0.0,1.0,0.1,...,1.1,4.0,2.4,11.0,1.8,9.5,0.3,36.0,0.2,3.0

In [3]:
drug.describe()

,n,alcohol-use,alcohol-frequency,marijuana-use,marijuana-frequency,cocaine-use,crack-use,heroin-use,hallucinogen-use,hallucinogen-frequency,...,pain-releiver-use,pain-releiver-frequency,oxycontin-use,tranquilizer-use,tranquilizer-frequency,stimulant-use,stimulant-frequency,meth-use,sedative-use,sedative-frequency
count,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,...,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000
mean,3251.058824,55.429412,33.352941,18.923529,42.941176,2.176471,0.294118,0.352941,3.394118,8.411765,...,6.270588,14.705882,0.935294,2.805882,11.735294,1.917647,31.147059,0.382353,0.282353,19.382353
std,1297.890426,26.878866,21.318833,11.959752,18.362566,1.816772,0.235772,0.333762,2.792506,15.000245,...,3.166379,6.935098,0.608216,1.753379,11.485205,1.407673,85.973790,0.262762,0.138000,24.833527
min,2223.000000,3.900000,3.000000,1.100000,4.000000,0.000000,0.000000,0.000000,0.100000,2.000000,...,0.600000,7.000000,0.000000,0.200000,4.500000,0.000000,2.000000,0.000000,0.000000,3.000000
25%,2469.000000,40.100000,10.000000,8.700000,30.000000,0.500000,0.000000,0.100000,0.600000,3.000000,...,3.900000,12.000000,0.400000,1.400000,6.000000,0.600000,7.000000,0.200000,0.200000,6.500000
50%,2798.000000,64.600000,48.000000,20.800000,52.000000,2.000000,0.400000,0.200000,3.200000,3.000000,...,6.200000,12.000000,1.100000,3.500000,10.000000,1.800000,10.000000,0.400000,0.300000,10.000000
75%,3058.000000,77.500000,52.000000,28.400000,52.000000,4.000000,0.500000,0.600000,5.200000,4.000000,...,9.000000,15.000000,1.400000,4.200000,11.000000,3.000000,12.000000,0.600000,0.400000,17.500000
max,7391.000000,84.200000,52.000000,34.000000,72.000000,4.900000,0.600000,1.100000,8.600000,52.000000,...,10.000000,36.000000,1.700000,5.400000,52.000000,4.100000,364.000000,0.900000,0.500000,104.000000

In [4]:
rows, cols = drug.shape # row and columns and save

In [5]:
drug.tail(10)

,n,alcohol-use,alcohol-frequency,marijuana-use,marijuana-frequency,cocaine-use,cocaine-frequency,crack-use,crack-frequency,heroin-use,...,oxycontin-use,oxycontin-frequency,tranquilizer-use,tranquilizer-frequency,stimulant-use,stimulant-frequency,meth-use,meth-frequency,sedative-use,sedative-frequency
age,,,,,,,,,,,,,,,,,,,,,
19,2223,64.6,36.0,33.4,60.0,4.1,5.5,0.5,2.0,0.5,...,1.5,7.5,4.2,4.5,3.3,6.0,0.4,105.0,0.3,6.0
20,2271,69.7,48.0,34.0,60.0,4.9,8.0,0.6,5.0,0.9,...,1.7,12.0,5.4,10.0,4.0,12.0,0.9,12.0,0.5,4.0
21,2354,83.2,52.0,33.0,52.0,4.8,5.0,0.5,17.0,0.6,...,1.3,13.5,3.9,7.0,4.1,10.0,0.6,2.0,0.3,9.0
22-23,4707,84.2,52.0,28.4,52.0,4.5,5.0,0.5,5.0,1.1,...,1.7,17.5,4.4,12.0,3.6,10.0,0.6,46.0,0.2,52.0
24-25,4591,83.1,52.0,24.9,60.0,4.0,6.0,0.5,6.0,0.7,...,1.3,20.0,4.3,10.0,2.6,10.0,0.7,21.0,0.2,17.5
26-29,2628,80.7,52.0,20.8,52.0,3.2,5.0,0.4,6.0,0.6,...,1.2,13.5,4.2,10.0,2.3,7.0,0.6,30.0,0.4,4.0
30-34,2864,77.5,52.0,16.4,72.0,2.1,8.0,0.5,15.0,0.4,...,0.9,46.0,3.6,8.0,1.4,12.0,0.4,54.0,0.4,10.0
35-49,7391,75.0,52.0,10.4,48.0,1.5,15.0,0.5,48.0,0.1,...,0.3,12.0,1.9,6.0,0.6,24.0,0.2,104.0,0.3,10.0
50-64,3923,67.2,52.0,7.3,52.0,0.9,36.0,0.4,62.0,0.1,...,0.4,5.0,1.4,10.0,0.3,24.0,0.2,30.0,0.2,104.0
65+,2448,49.3,52.0,1.2,36.0,0.0,-,0.0,-,0.0,...,0.0,-,0.2,5.0,0.0,364.0,0.0,-,0.0,15.0

In [6]:
drug.columns

Index(['n', 'alcohol-use', 'alcohol-frequency', 'marijuana-use',
       'marijuana-frequency', 'cocaine-use', 'cocaine-frequency', 'crack-use',
       'crack-frequency', 'heroin-use', 'heroin-frequency', 'hallucinogen-use',
       'hallucinogen-frequency', 'inhalant-use', 'inhalant-frequency',
       'pain-releiver-use', 'pain-releiver-frequency', 'oxycontin-use',
       'oxycontin-frequency', 'tranquilizer-use', 'tranquilizer-frequency',
       'stimulant-use', 'stimulant-frequency', 'meth-use', 'meth-frequency',
       'sedative-use', 'sedative-frequency'],
      dtype='object')

In [7]:
#drug. . and tab to see all. 
#shift tab twice VERY IMPORTANT!!!!

drug['alcohol-use'].head()

age
12     3.9
13     8.5
14    18.1
15    29.2
16    40.1
Name: alcohol-use, dtype: float64

In [8]:
drug[['alcohol-use']].head() #get a dataframe

     alcohol-use
age
12           3.9
13           8.5
14          18.1
15          29.2
16          40.1

In [9]:
print(type('alcohol-use'))

<class 'str'>

In [10]:
drug['alcohol-use'].unique()

array([ 3.9,  8.5, 18.1, 29.2, 40.1, 49.3, 58.7, 64.6, 69.7, 83.2, 84.2,
       83.1, 80.7, 77.5, 75. , 67.2])

In [11]:
#print((type(drug['age'])))

KeyError: 'age'

In [ ]:
drug.info()

In [ ]:
#esc and enter(return)
drug[['age']].describe()
##homework to do the subset change from object to int??

In [ ]:
drug.groupby('age').count()

In [ ]:
drug[drug.crack_use == 'crack-use'].groupby(['age', 'heroin-use']).count()
#article_read[article_read.country == 'country_2'].groupby(['source', 'topic']).count()

In [ ]:
diamonds = pd.read_csv('datasets/diamonds.csv')
print

In [ ]:
drug[(drug['age']>20) & (drug.n > 4000)]

In [ ]:
data = {
    'apples': [3, 2, 0, 1], 
    'oranges': [0, 3, 7, 2]
}

In [ ]:
purchases = pd.DataFrame(data)

purchases

purchases = pd.DataFrame(data, index=['June', 'Robert', 'Lily', 'David'])

purchases

purchases.loc['June']

In [ ]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

In [ ]:
s.index

In [ ]:
s = pd.Series(['Tiger', 'Bear', 'Moose'], index=['India', 'America', 'Canada'])
s

In [ ]:
len(df[(df['Price'] > 0) | (df['Price'] > 0)])

In [ ]:
#import all the diamond csv
diamond= pd.read_csv('datasets/diamonds.csv')
# Get the name of the CSV.
diamond.columns

In [ ]:
# Convert diamond carat to Series (Series can only ever have 1 column (plus an index).)
dc = diamond['carat'][:10] #only wanted 10 rows since it too much. 
pd.Series(dc)

# sample code
# data = np.random.rand(5)
# pd.Series(data)

In [ ]:
diamond.head(2)

In [ ]:
diamond2 = pd.DataFrame(diamond,index=['A', 'B', 'C', 'D', 'E'],columns=['I get to choose the name', 'col2', 'col3', 'col4', 'col5'])
diamond2

In [ ]:
#I was testing lamda.
diamond.index = [lambda:i for i in range(53940)]
diamond.head(5)

In [ ]:
# using the np range from 1 to 53940 an index.
diamond.index = np.arange(1,53941) 
diamond.head(5)

tomorrow to do the sum and equations.